// @ts-check
import { fileURLToPath } from "node:url";
import path from "node:path";
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import eslintPluginAstro from "eslint-plugin-astro";

// import.meta.dirname needs Node 21.2+ and matching @types/node typings;
// fileURLToPath is portable across the Node versions this project supports.
const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default tseslint.config(
  // Don't lint build output, generated types, or stale local artifacts.
  {
    ignores: ["dist/", ".astro/", ".netlify/", "node_modules/"],
  },

  // Base JS + type-aware TypeScript rules.
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  // Astro components. Wires up astro-eslint-parser, the recommended Astro
  // rules, and (via parserOptions below) the TS frontmatter type information.
  ...eslintPluginAstro.configs.recommended,

  // Enable type-aware linting. `projectService` resolves each file against the
  // nearest tsconfig automatically; `.astro` files need to be declared as an
  // extra extension so the TS program will include their frontmatter.
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
        extraFileExtensions: [".astro"],
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  // The TS compiler already resolves ambient types (e.g. `ImageMetadata`), so
  // core `no-undef` only produces false positives on typed Astro frontmatter.
  {
    files: ["**/*.astro"],
    rules: {
      "no-undef": "off",
    },
  },

  // env.d.ts is generated by Astro and uses triple-slash references by design.
  {
    files: ["**/*.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },

  // Turn off the type-aware rules where full type information isn't reliably
  // available:
  //   - .astro frontmatter: astro-eslint-parser can't reconstruct Astro's
  //     generated content-collection types, so getCollection() etc. surface
  //     as unresolved `any` and trip every no-unsafe-* rule (false positives).
  //   - JS config/scripts live outside the typed project entirely.
  {
    files: ["**/*.astro", "**/*.{js,mjs,cjs}"],
    extends: [tseslint.configs.disableTypeChecked],
  },
);
